---

- name: Install WebServer on Redhat Distro
  hosts: Redhat
  remote_user: root

  tasks:
    - name: Ensure Apache is at the latest version
      yum:
        name: httpd
        state: latest
    - name: Ensure Apache is enable & running 
      service:
        name: httpd
        state: started
        enabled: yes 

- name: Install WebServer on Debian Distro
  hosts: Debian
  remote_user: root

  tasks:
    - name: Ensure Apache is at the latest version
      apt:
        name: apache2
        state: latest
    - name: Ensure Apache is enable & running 
      service:
        name: apache2
        state: started
        enabled: yes 